# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: tienda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
# environment:
#   DB_DIALECT: "mysql"
#   DB_NAME: "tienda"
#   DB_USERNAME: "root"
#   DB_PASSWORD: ""
#   DB_HOST: "127.0.0.1" #!GetAtt myDB.Endpoint.Address
#   DB_PORT: "3306"


# you can add packaging information here
package:
 patterns:
   - '!node_modules'
   - '!exclude-me-dir/**'
 

functions:
  # Archivo de apis
  ObtenerUsusario:
    handler: src/Usuarios/Get.Get
    events:
    - http:
        method: GET
        path: /Usuario/
        cors: true
  crearUsusario:
    handler: src/Usuarios/Post.Post
    events:
    - http:
        method: Post
        path: /Usuario/
        cors: true
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
